<a href="https://colab.research.google.com/github/marcomoretto/physalia_python_2022/blob/main/Lesson_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analysis with Python

### NumPy
NumPy, short for Numerical Python, has long been a cornerstone of numerical computing in Python. It provides the data structures, algorithms, and library glue needed for most scientific applications involving numerical data in Python

### pandas
pandas provides high-level data structures and functions designed to make working with structured or tabular data fast, easy, and expressive. The primary objects in pandas is the DataFrame, a tabular, column-oriented data structure with both row and column labels. pandas blends the high-performance, array-computing ideas of NumPy with the flexible data manipulation capabilities of spreadsheets and relational databases.

### matplotlib, seaborn, altair, plotly, bokeh, holoview, hvPlot and plotnine
matplotlib is the most popular Python library for producing plots and other two-dimensional data visualizations. seaborn is a library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics. altair is a declarative statistical visualization library for Python, based on Vega and Vega-Lite. plotly.py is an interactive, open-source, and browser-based graphing library for Python. Bokeh is a Python library for creating interactive visualizations for modern web browsers. HoloViews is a concise declarative interface that helps you build Bokeh plots. It is a separately maintained package that focuses on interaction with Jupyter notebooks and enables quick prototyping of figures for data analysis. hvPlot is a concise API that lets you plot in Bokeh with the pandas .plot() function and a wide variety of data containers. This API is particularly convenient for working with data interactively and lets you quickly produce common types of plots. Plotnine is a Python implementation of the Grammar of Graphics and follows the same idea (and syntax) of ggplot2 in R.

# Numpy

In [ ]:
import numpy as np

### The basic object is an N-dimensional array object, or `ndarray`. An `ndarray` is a generic multidimensional container for homogeneous data.

In [ ]:
a = np.array(['ciao', 1.0, True])

In [ ]:
type(a), type(a[0]), type(a[1]), type(a[2])

(numpy.ndarray, numpy.str_, numpy.str_, numpy.str_)

In [ ]:
[1, 2] * 2

[1, 2, 1, 2]

In [ ]:
np.array([1, 2]) * 2

array([2, 4])

### NumPy is more efficient than pure Python when dealing with number crunching

In [ ]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 17.1 ms, sys: 7.14 ms, total: 24.2 ms
Wall time: 25.5 ms


In [ ]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 797 ms, sys: 189 ms, total: 986 ms
Wall time: 989 ms


#### Let's see some arithmetic operations

In [ ]:
data = np.random.randn(2, 3)
data

array([[ 1.23720106, -0.91453734,  0.48735197],
       [-0.30959949,  0.55286455, -1.22797842]])

In [ ]:
data + 2

array([[3.23720106, 1.08546266, 2.48735197],
       [1.69040051, 2.55286455, 0.77202158]])

In [ ]:
data * 2

array([[ 2.47440211, -1.82907469,  0.97470394],
       [-0.61919897,  1.10572911, -2.45595684]])

In [ ]:
data + data

array([[ 2.47440211, -1.82907469,  0.97470394],
       [-0.61919897,  1.10572911, -2.45595684]])

In [ ]:
data * data

array([[1.53066645, 0.83637855, 0.23751194],
       [0.09585184, 0.30565921, 1.507931  ]])

In [ ]:
data ** 2

array([[1.53066645, 0.83637855, 0.23751194],
       [0.09585184, 0.30565921, 1.507931  ]])

In [ ]:
data.shape

(2, 3)

In [ ]:
data

array([[ 1.23720106, -0.91453734,  0.48735197],
       [-0.30959949,  0.55286455, -1.22797842]])

In [ ]:
data.T.shape

(3, 2)

In [ ]:
np.dot(data, data.T)

array([[ 2.60455695, -1.48710979],
       [-1.48710979,  1.90944206]])

In [ ]:
v1 = np.random.randn(5, )
v2 = np.random.randn(5, )

In [ ]:
v2

array([-0.98971827, -0.15600512, -0.08797385,  0.25658233, -0.89198758])

In [ ]:
np.dot(v1, v2)

1.4049860412874398

### Shape, indexing and slicing

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a[:3]

array([0, 1, 2])

In [ ]:
a[3:-2]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[3:-2:2]

array([3, 5, 7, 9])

In [ ]:
# i= 0    1    2    3    4    5    6    7    8    9   10   11
# ┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┐
# │  0 │  1 │  2 │  3 │  4 │  5 │  6 │  7 │  8 │  9 │ 10 │ 11 │
# └────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┘

In [ ]:
a.shape

(12,)

In [ ]:
a.ndim == len(a.shape)

True

In [ ]:
b = a.reshape((3, 4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# i= 0    0    0    0    1    1    1    1    2    2    2    2
# j= 0    1    2    3    0    1    2    3    0    1    2    3
# ┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┐
# │  0 │  1 │  2 │  3 │  4 │  5 │  6 │  7 │  8 │  9 │ 10 │ 11 │
# └────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┘

In [ ]:
b[1, 2]

6

In [ ]:
b[1,]

array([4, 5, 6, 7])

In [ ]:
c = a.reshape((2, 3, 2))
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
# i= 0    0    0    0    0    0    1    1    1    1    1    1
# j= 0    0    1    1    2    2    0    0    1    1    2    2
# k= 0    1    0    1    0    1    0    1    0    1    0    1
# ┌────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┬────┐
# │  0 │  1 │  2 │  3 │  4 │  5 │  6 │  7 │  8 │  9 │ 10 │ 11 │
# └────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┴────┘

In [ ]:
c[0, 2, 1]

5

In [ ]:
c[0, 2, 1]

In [ ]:
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Boolean indexing

In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b.shape

(3, 4)

In [ ]:
b[0]

array([0, 1, 2, 3])

In [ ]:
b[0][1]

1

In [ ]:
b[0, 1]

1

In [ ]:
p_array = [1, 2, 3, 4, 5]
np_array = np.array(p_array)

type(p_array), type(np_array)

(list, numpy.ndarray)

In [ ]:
p_array[0], np_array[0]

(1, 1)

In [ ]:
indexes = [0, 2]

In [ ]:
np_array[indexes]

array([1, 3])

In [ ]:
p_array[indexes]

TypeError: ignored

In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[indexes, ]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [ ]:
b[indexes]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [ ]:
b[:,indexes]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

data

array([[-0.85548968, -0.53724736,  0.36601183, -0.01667593],
       [-0.00901614,  0.06340822,  0.58007293,  0.81172839],
       [ 0.19698339,  0.84864644, -0.26848785, -0.35498599],
       [ 1.13230168, -1.08393766, -1.63890633, -0.21438895],
       [-0.11198484, -0.47538305,  0.31544562,  0.64568185],
       [ 1.45376024,  0.76881544,  1.36216349, -0.77367693],
       [-1.03391399,  1.29224998,  0.16671244, -0.23719906]])

In [ ]:
names.reshape(7, 1)

array([['Bob'],
       ['Joe'],
       ['Will'],
       ['Bob'],
       ['Will'],
       ['Joe'],
       ['Joe']], dtype='<U4')

In [ ]:
np.array([1,2,3,4]) + 5

array([6, 7, 8, 9])

In [ ]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [ ]:
(names == 'Bob').reshape(7,1)

array([[ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False]])

In [ ]:
data[names == 'Bob']

array([[-0.85548968, -0.53724736,  0.36601183, -0.01667593],
       [ 1.13230168, -1.08393766, -1.63890633, -0.21438895]])

In [ ]:
data[names == 'Bob', :2]

array([[-0.85548968, -0.53724736],
       [ 1.13230168, -1.08393766]])

In [ ]:
data < 0

array([[ True,  True, False,  True],
       [ True, False, False, False],
       [False, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False,  True],
       [ True, False, False,  True]])

In [ ]:
data[data < 0]

array([-0.85548968, -0.53724736, -0.01667593, -0.00901614, -0.26848785,
       -0.35498599, -1.08393766, -1.63890633, -0.21438895, -0.11198484,
       -0.47538305, -0.77367693, -1.03391399, -0.23719906])

In [ ]:
data[data < 0] = 0

In [ ]:
data

array([[0.        , 0.        , 0.36601183, 0.        ],
       [0.        , 0.06340822, 0.58007293, 0.81172839],
       [0.19698339, 0.84864644, 0.        , 0.        ],
       [1.13230168, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.31544562, 0.64568185],
       [1.45376024, 0.76881544, 1.36216349, 0.        ],
       [0.        , 1.29224998, 0.16671244, 0.        ]])

### Broadcasting

Arrays with different sizes cannot be added, subtracted, or generally be used in arithmetic.

A way to overcome this is to duplicate the smaller array so that it is the dimensionality and size as the larger array.

* if the array shapes have different lengths, then left-pad the smaller shape with 1;
* if any corresponding dimension does not match, make copies along the 1-dimension
* if any corresponding dimension does not have a 1 in it, raise an error

In [ ]:
np.array(1) # zero dimensional array

array(1)

In [ ]:
np.array(1).ndim

0

In [ ]:
np.array([1]) # one dimensional array

array([1])

In [ ]:
# scalar with zero dimensional array
x = np.arange(5)

x * 5

array([ 0,  5, 10, 15, 20])

In [ ]:
x

array([0, 1, 2, 3, 4])

In [ ]:
np.full((5,), 5)

array([5, 5, 5, 5, 5])

In [ ]:
x * np.full((5,), 5)

array([ 0,  5, 10, 15, 20])

In [ ]:
x = np.arange(10).reshape(2, 5) # scalar and 2-dimensional array

x * 5

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [ ]:
x * np.full((5,), 5)

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [ ]:
x * np.full((1, 5), 5)

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [ ]:
np.full((2, 5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
x * np.full((2, 5), 5)

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [ ]:
x = np.arange(3)
y = np.arange(3)

In [ ]:
x * y

array([0, 1, 4])

In [ ]:
x = np.arange(3)
y = np.arange(5)

In [ ]:
x

array([0, 1, 2])

In [ ]:
y

array([0, 1, 2, 3, 4])

In [ ]:
x * y

ValueError: ignored

In [ ]:
# element-wise product 'by hand'
out = []
for i in x:
  for j in y:
    out.append(i * j)
out # we lost the information about dimensions

[0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 0, 2, 4, 6, 8]

In [ ]:
np.array(out).reshape(len(x), -1)

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [ ]:
# we can reshape the output
np.array(out).reshape(len(x), len(y))
# or use
np.array(out).reshape(len(x), -1) # -1 means infer the rest

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [ ]:
x

array([0, 1, 2])

In [ ]:
y

array([0, 1, 2, 3, 4])

In [ ]:
x[:,np.newaxis] * y

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [ ]:
x.reshape((3,1)) * y

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [ ]:
x.reshape((3,1)) * np.array([y, y, y])

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [ ]:
x[:,np.newaxis] * y

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [ ]:
x.reshape(3, 1) * y

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [ ]:
x * y[:,np.newaxis]

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6],
       [0, 4, 8]])

In [ ]:
x = np.arange(10).reshape(2, 5)
y = np.arange(12)

x * y

ValueError: ignored

In [ ]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
x = np.arange(10).reshape(2, 5)
y = np.arange(12).reshape(3, 4)

In [ ]:
x * y

ValueError: ignored

In [ ]:
(x[:,:,np.newaxis,np.newaxis] * y).shape

(2, 5, 3, 4)

In [ ]:
x = np.arange(10).reshape(2, 5)
y = np.arange(12).reshape(3, 4)

y[:,:,np.newaxis, np.newaxis] * x

array([[[[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[ 0,  2,  4,  6,  8],
         [10, 12, 14, 16, 18]],

        [[ 0,  3,  6,  9, 12],
         [15, 18, 21, 24, 27]]],


       [[[ 0,  4,  8, 12, 16],
         [20, 24, 28, 32, 36]],

        [[ 0,  5, 10, 15, 20],
         [25, 30, 35, 40, 45]],

        [[ 0,  6, 12, 18, 24],
         [30, 36, 42, 48, 54]],

        [[ 0,  7, 14, 21, 28],
         [35, 42, 49, 56, 63]]],


       [[[ 0,  8, 16, 24, 32],
         [40, 48, 56, 64, 72]],

        [[ 0,  9, 18, 27, 36],
         [45, 54, 63, 72, 81]],

        [[ 0, 10, 20, 30, 40],
         [50, 60, 70, 80, 90]],

        [[ 0, 11, 22, 33, 44],
         [55, 66, 77, 88, 99]]]])

# Pandas

In [ ]:
import pandas as pd

s = pd.Series([5, 6, 7, 8])
s

0    5
1    6
2    7
3    8
dtype: int64

In [ ]:
s = pd.Series([5, 6, 7, 8], index=['a', 'b', 'c', 'd'])
s

a    5
b    6
c    7
d    8
dtype: int64

In [ ]:
d = {'a': 5, 'b':6, 'c':7, 'd':8}
d

{'a': 5, 'b': 6, 'c': 7, 'd': 8}

In [ ]:
s = pd.Series(d)
s

a    5
b    6
c    7
d    8
dtype: int64

In [ ]:
s[['a', 'd']]

a    5
d    8
dtype: int64

In [ ]:
d[['a', 'd']]

TypeError: ignored

In [ ]:
d > 6

TypeError: ignored

In [ ]:
s[s > 6]

c    7
d    8
dtype: int64

In [ ]:
d[d > 6]

TypeError: ignored

### A DataFrame can be tought as a dictionary of Series sharing an index


In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003]}

In [ ]:
df = pd.DataFrame(data)
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
# let's specify a different index
# index are immutable and can hold duplicated values. They also behave like a list
df = pd.DataFrame(data, index=['first', 'second', 'third', 'fourth', 'fifth', 'sixth'])
df

state  year  pop
first     Ohio  2000  1.5
second    Ohio  2001  1.7
third     Ohio  2002  3.6
fourth  Nevada  2001  2.4
fifth   Nevada  2002  2.9
sixth   Nevada  2003  3.2

In [ ]:
df['year']

first     2000
second    2001
third     2002
fourth    2001
fifth     2002
sixth     2003
Name: year, dtype: int64

In [ ]:
df.year

first     2000
second    2001
third     2002
fourth    2001
fifth     2002
sixth     2003
Name: year, dtype: int64

In [ ]:
df.loc['third']

state    Ohio
year     2002
pop       3.6
Name: third, dtype: object

In [ ]:
df.head(2)

state  year  pop
first   Ohio  2000  1.5
second  Ohio  2001  1.7

In [ ]:
df['debt'] = np.nan

In [ ]:
df

state  year  pop  debt
first     Ohio  2000  1.5   NaN
second    Ohio  2001  1.7   NaN
third     Ohio  2002  3.6   NaN
fourth  Nevada  2001  2.4   NaN
fifth   Nevada  2002  2.9   NaN
sixth   Nevada  2003  3.2   NaN

In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index=['second', 'fourth', 'fifth'])
df['debt_2'] = val
df

state  year  pop  debt  debt_2
first     Ohio  2000  1.5   NaN     NaN
second    Ohio  2001  1.7   NaN    -1.2
third     Ohio  2002  3.6   NaN     NaN
fourth  Nevada  2001  2.4   NaN    -1.5
fifth   Nevada  2002  2.9   NaN    -1.7
sixth   Nevada  2003  3.2   NaN     NaN

In [ ]:
df['eastern'] = df['state'] == 'Ohio'
df

state  year  pop  debt  debt_2  eastern
first     Ohio  2000  1.5   NaN     NaN     True
second    Ohio  2001  1.7   NaN    -1.2     True
third     Ohio  2002  3.6   NaN     NaN     True
fourth  Nevada  2001  2.4   NaN    -1.5    False
fifth   Nevada  2002  2.9   NaN    -1.7    False
sixth   Nevada  2003  3.2   NaN     NaN    False

In [ ]:
df['new_column'] = pd.Series(np.arange(10))

In [ ]:
df

state  year  pop  debt  debt_2  eastern  new_column
first     Ohio  2000  1.5   NaN     NaN     True         NaN
second    Ohio  2001  1.7   NaN    -1.2     True         NaN
third     Ohio  2002  3.6   NaN     NaN     True         NaN
fourth  Nevada  2001  2.4   NaN    -1.5    False         NaN
fifth   Nevada  2002  2.9   NaN    -1.7    False         NaN
sixth   Nevada  2003  3.2   NaN     NaN    False         NaN

In [ ]:
del df['eastern']
df

state  year  pop  debt  debt_2  new_column
first     Ohio  2000  1.5   NaN     NaN         NaN
second    Ohio  2001  1.7   NaN    -1.2         NaN
third     Ohio  2002  3.6   NaN     NaN         NaN
fourth  Nevada  2001  2.4   NaN    -1.5         NaN
fifth   Nevada  2002  2.9   NaN    -1.7         NaN
sixth   Nevada  2003  3.2   NaN     NaN         NaN

In [ ]:
df.values

array([['Ohio', 2000, 1.5, nan, nan, nan],
       ['Ohio', 2001, 1.7, nan, -1.2, nan],
       ['Ohio', 2002, 3.6, nan, nan, nan],
       ['Nevada', 2001, 2.4, nan, -1.5, nan],
       ['Nevada', 2002, 2.9, nan, -1.7, nan],
       ['Nevada', 2003, 3.2, nan, nan, nan]], dtype=object)

In [ ]:
df.T

first second third  fourth   fifth   sixth
state       Ohio   Ohio  Ohio  Nevada  Nevada  Nevada
year        2000   2001  2002    2001    2002    2003
pop          1.5    1.7   3.6     2.4     2.9     3.2
debt         NaN    NaN   NaN     NaN     NaN     NaN
debt_2       NaN   -1.2   NaN    -1.5    -1.7     NaN
new_column   NaN    NaN   NaN     NaN     NaN     NaN

In [ ]:
df1 = df.set_index('year')
df1

state  pop  debt  debt_2  new_column
year                                       
2000    Ohio  1.5   NaN     NaN         NaN
2001    Ohio  1.7   NaN    -1.2         NaN
2002    Ohio  3.6   NaN     NaN         NaN
2001  Nevada  2.4   NaN    -1.5         NaN
2002  Nevada  2.9   NaN    -1.7         NaN
2003  Nevada  3.2   NaN     NaN         NaN

In [ ]:
idx = list(df.index)
np.random.shuffle(idx)
print(list(df.index))
print(idx)

['first', 'second', 'third', 'fourth', 'fifth', 'sixth']
['second', 'first', 'third', 'fifth', 'sixth', 'fourth']


In [ ]:
df

state  year  pop  debt  debt_2  new_column
first     Ohio  2000  1.5   NaN     NaN         NaN
second    Ohio  2001  1.7   NaN    -1.2         NaN
third     Ohio  2002  3.6   NaN     NaN         NaN
fourth  Nevada  2001  2.4   NaN    -1.5         NaN
fifth   Nevada  2002  2.9   NaN    -1.7         NaN
sixth   Nevada  2003  3.2   NaN     NaN         NaN

In [ ]:
df.reindex(idx)

state  year  pop  debt  debt_2  new_column
second    Ohio  2001  1.7   NaN    -1.2         NaN
first     Ohio  2000  1.5   NaN     NaN         NaN
third     Ohio  2002  3.6   NaN     NaN         NaN
fifth   Nevada  2002  2.9   NaN    -1.7         NaN
sixth   Nevada  2003  3.2   NaN     NaN         NaN
fourth  Nevada  2001  2.4   NaN    -1.5         NaN

In [ ]:
idx.append('seventh')
df.reindex(idx)

state    year  pop  debt  debt_2  new_column
second     Ohio  2001.0  1.7   NaN    -1.2         NaN
first      Ohio  2000.0  1.5   NaN     NaN         NaN
third      Ohio  2002.0  3.6   NaN     NaN         NaN
fifth    Nevada  2002.0  2.9   NaN    -1.7         NaN
sixth    Nevada  2003.0  3.2   NaN     NaN         NaN
fourth   Nevada  2001.0  2.4   NaN    -1.5         NaN
seventh     NaN     NaN  NaN   NaN     NaN         NaN

In [ ]:
# drop columns or rows
df.drop(['state'], axis=1)

year  pop  debt  debt_2  new_column
first   2000  1.5   NaN     NaN         NaN
second  2001  1.7   NaN    -1.2         NaN
third   2002  3.6   NaN     NaN         NaN
fourth  2001  2.4   NaN    -1.5         NaN
fifth   2002  2.9   NaN    -1.7         NaN
sixth   2003  3.2   NaN     NaN         NaN

In [ ]:
df = df.drop(['state'], axis=1)

In [ ]:
df

year  pop  debt  debt_2  new_column
first   2000  1.5   NaN     NaN         NaN
second  2001  1.7   NaN    -1.2         NaN
third   2002  3.6   NaN     NaN         NaN
fourth  2001  2.4   NaN    -1.5         NaN
fifth   2002  2.9   NaN    -1.7         NaN
sixth   2003  3.2   NaN     NaN         NaN

In [ ]:
df.drop(['first', 'sixth'], axis=0)

year  pop  debt  debt_2  new_column
second  2001  1.7   NaN    -1.2         NaN
third   2002  3.6   NaN     NaN         NaN
fourth  2001  2.4   NaN    -1.5         NaN
fifth   2002  2.9   NaN    -1.7         NaN

In [ ]:
# selection and slicing
df[:2] # for convenience it works on rows

year  pop  debt  debt_2  new_column
first   2000  1.5   NaN     NaN         NaN
second  2001  1.7   NaN    -1.2         NaN

In [ ]:
df.iloc[:2]

year  pop  debt  debt_2  new_column
first   2000  1.5   NaN     NaN         NaN
second  2001  1.7   NaN    -1.2         NaN

In [ ]:
df.iloc[:, :2]

year  pop
first   2000  1.5
second  2001  1.7
third   2002  3.6
fourth  2001  2.4
fifth   2002  2.9
sixth   2003  3.2

In [ ]:
samples = ['sample_' + str(x) for x in range(1,6)]
variables = [chr(x) for x in range(97, 102)]

df2 = pd.DataFrame(np.random.rand(5,5), index=samples, columns=variables)

In [ ]:
df2

a         b         c         d         e
sample_1  0.060971  0.797469  0.694987  0.485028  0.983449
sample_2  0.586593  0.272913  0.246867  0.214747  0.544799
sample_3  0.133923  0.023765  0.328263  0.159806  0.687147
sample_4  0.590041  0.613889  0.523715  0.013228  0.438430
sample_5  0.336381  0.396756  0.576296  0.018135  0.300187

In [ ]:
df2 > 0.5

a      b      c      d      e
sample_1  False   True   True  False   True
sample_2   True  False  False  False   True
sample_3  False  False  False  False   True
sample_4   True   True   True  False  False
sample_5  False  False   True  False  False

In [ ]:
df2[df2 > 0.5]

a         b         c   d         e
sample_1       NaN  0.797469  0.694987 NaN  0.983449
sample_2  0.586593       NaN       NaN NaN  0.544799
sample_3       NaN       NaN       NaN NaN  0.687147
sample_4  0.590041  0.613889  0.523715 NaN       NaN
sample_5       NaN       NaN  0.576296 NaN       NaN

In [ ]:
df2[df2 > 0.5] = 1
df2

a         b         c         d         e
sample_1  0.060971  1.000000  1.000000  0.485028  1.000000
sample_2  1.000000  0.272913  0.246867  0.214747  1.000000
sample_3  0.133923  0.023765  0.328263  0.159806  1.000000
sample_4  1.000000  1.000000  1.000000  0.013228  0.438430
sample_5  0.336381  0.396756  1.000000  0.018135  0.300187

In [ ]:
df

year  pop  debt  debt_2  new_column
first   2000  1.5   NaN     NaN         NaN
second  2001  1.7   NaN    -1.2         NaN
third   2002  3.6   NaN     NaN         NaN
fourth  2001  2.4   NaN    -1.5         NaN
fifth   2002  2.9   NaN    -1.7         NaN
sixth   2003  3.2   NaN     NaN         NaN

In [ ]:
df.loc[['second', 'fourth'], ['year', 'debt']]

year  debt
second  2001   NaN
fourth  2001   NaN

In [ ]:
df.iloc[[1,3], [1,3]]

pop  debt_2
second  1.7    -1.2
fourth  2.4    -1.5

### Arithmetics

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

df1.loc[1, 'b'] = np.nan
df2.loc[2, 'c'] = np.nan


df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  NaN   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0   NaN  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0   NaN  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   6.0  13.0  15.0   9.0
2  18.0  20.0  10.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250       NaN  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
df1.rdiv(1, fill_value=1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  1.000000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

### Dealing with missing values

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

df1.loc[1, 'b'] = np.nan

In [ ]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  NaN   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df1.mean(axis=1).loc[1]

5.666666666666667

In [ ]:
df1.mean()

a    4.0
b    5.0
c    6.0
d    7.0
dtype: float64

In [ ]:
df1.fillna({'b': df1.mean(axis=1).loc[1]})

a         b     c     d
0  0.0  1.000000   2.0   3.0
1  4.0  5.666667   6.0   7.0
2  8.0  9.000000  10.0  11.0

In [ ]:
df1.fillna(df.mean(axis=1))

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  NaN   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df1.dropna()

a    b     c     d
0  0.0  1.0   2.0   3.0
2  8.0  9.0  10.0  11.0

In [ ]:
df1.dropna(axis=1)

a     c     d
0  0.0   2.0   3.0
1  4.0   6.0   7.0
2  8.0  10.0  11.0

In [ ]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  NaN   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df1.dropna(how='all')

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  NaN   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df1.dropna(axis=0, how='any', thresh=2)

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  NaN   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df1.loc[0, ['c', 'd']] = np.nan
df1

a    b     c     d
0  0.0  1.0   NaN   NaN
1  4.0  NaN   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df1.dropna(axis=0, how='any', thresh=3)

a    b     c     d
1  4.0  NaN   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df1.shape[1] * 0.8

3.2

In [ ]:
df1.dropna(axis=0, how='any', thresh=df1.shape[1] * 0.8)

a    b     c     d
2  8.0  9.0  10.0  11.0

### Apply functions

In [ ]:
# NumPy ufuncs (element-wise array methods) also work with pandas objects
np.mean(df1, axis=1)

0    0.500000
1    5.666667
2    9.500000
dtype: float64

In [ ]:
df1.mean(axis=1)

0    0.500000
1    5.666667
2    9.500000
dtype: float64

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0   NaN  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df2.apply(lambda x : x.max() - x.min(), axis=1)

0    4.0
1    4.0
2    4.0
3    4.0
dtype: float64

In [ ]:
df2.apply(lambda x : pd.Series([x.max(), x.min()], index=['max', 'min']), axis=1)

max   min
0   4.0   0.0
1   9.0   5.0
2  14.0  10.0
3  19.0  15.0

In [ ]:
df2.mean()

a     7.500000
b     8.500000
c     8.666667
d    10.500000
e    11.500000
dtype: float64

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0   NaN  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df2.agg(['mean', 'min', 'max'], axis=1)

mean   min   max
0   2.0   0.0   4.0
1   7.0   5.0   9.0
2  12.0  10.0  14.0
3  17.0  15.0  19.0

In [ ]:
df2.agg(['mean', lambda x : x.min(), lambda x : x.max()], axis=1)

mean  <lambda>  <lambda>
0   2.0       0.0       4.0
1   7.0       5.0       9.0
2  12.0      10.0      14.0
3  17.0      15.0      19.0

In [ ]:
df2.agg(x=('a', 'mean'), axis=0)

a
x  7.5

### Sorting

In [ ]:
np.random.shuffle(samples)
np.random.shuffle(variables)

df2 = pd.DataFrame(np.random.rand(5,5), index=samples, columns=variables)
df2

a         b         d         e         c
sample_2  0.392935  0.793858  0.835363  0.953199  0.979439
sample_4  0.098754  0.529040  0.639846  0.503015  0.670308
sample_1  0.186488  0.166860  0.305457  0.873993  0.110563
sample_5  0.177625  0.161430  0.553927  0.556781  0.521121
sample_3  0.828865  0.008656  0.846051  0.193573  0.068596

In [ ]:
df2.sort_index(axis=1).sort_index(axis=0)

a         b         c         d         e
sample_1  0.186488  0.166860  0.110563  0.305457  0.873993
sample_2  0.392935  0.793858  0.979439  0.835363  0.953199
sample_3  0.828865  0.008656  0.068596  0.846051  0.193573
sample_4  0.098754  0.529040  0.670308  0.639846  0.503015
sample_5  0.177625  0.161430  0.521121  0.553927  0.556781

In [ ]:
df2.sort_values(by='a')

a         b         d         e         c
sample_4  0.098754  0.529040  0.639846  0.503015  0.670308
sample_5  0.177625  0.161430  0.553927  0.556781  0.521121
sample_1  0.186488  0.166860  0.305457  0.873993  0.110563
sample_2  0.392935  0.793858  0.835363  0.953199  0.979439
sample_3  0.828865  0.008656  0.846051  0.193573  0.068596

In [ ]:
df2.loc['sample_2','a'] = df2.loc['sample_4','a'] 
df2

a         b         d         e         c
sample_2  0.098754  0.793858  0.835363  0.953199  0.979439
sample_4  0.098754  0.529040  0.639846  0.503015  0.670308
sample_1  0.186488  0.166860  0.305457  0.873993  0.110563
sample_5  0.177625  0.161430  0.553927  0.556781  0.521121
sample_3  0.828865  0.008656  0.846051  0.193573  0.068596

In [ ]:
df2.sort_values(by='a')

a         b         d         e         c
sample_2  0.098754  0.793858  0.835363  0.953199  0.979439
sample_4  0.098754  0.529040  0.639846  0.503015  0.670308
sample_5  0.177625  0.161430  0.553927  0.556781  0.521121
sample_1  0.186488  0.166860  0.305457  0.873993  0.110563
sample_3  0.828865  0.008656  0.846051  0.193573  0.068596

In [ ]:
df2.sort_values(by=['a', 'd'])

a         b         d         e         c
sample_4  0.098754  0.529040  0.639846  0.503015  0.670308
sample_2  0.098754  0.793858  0.835363  0.953199  0.979439
sample_5  0.177625  0.161430  0.553927  0.556781  0.521121
sample_1  0.186488  0.166860  0.305457  0.873993  0.110563
sample_3  0.828865  0.008656  0.846051  0.193573  0.068596

In [ ]:
df2.sort_values(by='sample_5', axis=1, ascending=False)

e         d         c         a         b
sample_2  0.953199  0.835363  0.979439  0.098754  0.793858
sample_4  0.503015  0.639846  0.670308  0.098754  0.529040
sample_1  0.873993  0.305457  0.110563  0.186488  0.166860
sample_5  0.556781  0.553927  0.521121  0.177625  0.161430
sample_3  0.193573  0.846051  0.068596  0.828865  0.008656

### Summarizing and descriptive statistics

In [ ]:
df2.describe()

a         b         d         e         c
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.278097  0.331969  0.636129  0.616112  0.470005
std    0.310709  0.321346  0.223538  0.306178  0.384898
min    0.098754  0.008656  0.305457  0.193573  0.068596
25%    0.098754  0.161430  0.553927  0.503015  0.110563
50%    0.177625  0.166860  0.639846  0.556781  0.521121
75%    0.186488  0.529040  0.835363  0.873993  0.670308
max    0.828865  0.793858  0.846051  0.953199  0.979439

In [ ]:
df2.count(axis=1)

sample_2    5
sample_4    5
sample_1    5
sample_5    5
sample_3    5
dtype: int64

In [ ]:
df2.sum(axis=1)

sample_2    3.660613
sample_4    2.440963
sample_1    1.643362
sample_5    1.970883
sample_3    1.945740
dtype: float64

In [ ]:
df2.agg(['count', 'mean', 'std'])

a         b         d         e         c
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.278097  0.331969  0.636129  0.616112  0.470005
std    0.310709  0.321346  0.223538  0.306178  0.384898

### Pandas I/O

In [ ]:
iris = pd.read_csv('https://datahub.io/machine-learning/iris/r/iris.csv')
iris

sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
iris = pd.read_excel('https://web.stanford.edu/~ashishg/msande111/excel/iris.xls')
iris

Unnamed: 0         Unnamed: 1  ... Unnamed: 10 Unnamed: 11
0           NaN  Sepal Length (cm)  ...         NaN         NaN
1           NaN                  7  ...         0.0         1.0
2           NaN                6.4  ...         0.0         1.0
3           NaN                6.9  ...         0.0         1.0
4           NaN                5.5  ...         0.0         1.0
..          ...                ...  ...         ...         ...
96          NaN                4.8  ...         0.0         1.0
97          NaN                5.1  ...         0.0         1.0
98          NaN                4.6  ...         0.0         1.0
99          NaN                5.3  ...         0.0         1.0
100         NaN                  5  ...         0.0         1.0

[101 rows x 12 columns]

In [ ]:
iris = pd.read_excel('https://web.stanford.edu/~ashishg/msande111/excel/iris.xls', skiprows=1)
iris = iris.drop(iris.columns[0], axis=1).drop(iris.columns[6:], axis=1)
iris

Sepal Length (cm)  Sepal Width (cm)  ...  Petal Width (cm)            Class
0                 7.0               3.2  ...               1.4  Iris-versicolor
1                 6.4               3.2  ...               1.5  Iris-versicolor
2                 6.9               3.1  ...               1.5  Iris-versicolor
3                 5.5               2.3  ...               1.3  Iris-versicolor
4                 6.5               2.8  ...               1.5  Iris-versicolor
..                ...               ...  ...               ...              ...
95                4.8               3.0  ...               0.3      Iris-setosa
96                5.1               3.8  ...               0.2      Iris-setosa
97                4.6               3.2  ...               0.2      Iris-setosa
98                5.3               3.7  ...               0.2      Iris-setosa
99                5.0               3.3  ...               0.2      Iris-setosa

[100 rows x 5 columns]

In [ ]:
penguin = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv')
penguin

species     island  bill_length_mm  ...  flipper_length_mm  body_mass_g     sex
0    Adelie  Torgersen            39.1  ...              181.0       3750.0    MALE
1    Adelie  Torgersen            39.5  ...              186.0       3800.0  FEMALE
2    Adelie  Torgersen            40.3  ...              195.0       3250.0  FEMALE
3    Adelie  Torgersen             NaN  ...                NaN          NaN     NaN
4    Adelie  Torgersen            36.7  ...              193.0       3450.0  FEMALE
..      ...        ...             ...  ...                ...          ...     ...
339  Gentoo     Biscoe             NaN  ...                NaN          NaN     NaN
340  Gentoo     Biscoe            46.8  ...              215.0       4850.0  FEMALE
341  Gentoo     Biscoe            50.4  ...              222.0       5750.0    MALE
342  Gentoo     Biscoe            45.2  ...              212.0       5200.0  FEMALE
343  Gentoo     Biscoe            49.9  ...              213.0       5400.0    MALE

[344 rows x 7 columns]

In [ ]:
penguin.groupby(['species', 'sex']).mean()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
species   sex                                                                  
Adelie    FEMALE       37.257534      17.621918         187.794521  3368.835616
          MALE         40.390411      19.072603         192.410959  4043.493151
Chinstrap FEMALE       46.573529      17.588235         191.735294  3527.205882
          MALE         51.094118      19.252941         199.911765  3938.970588
Gentoo    FEMALE       45.563793      14.237931         212.706897  4679.741379
          MALE         49.473770      15.718033         221.540984  5484.836066

In [ ]:
penguin.groupby(['species', 'sex']).apply(lambda x : np.mean(x['body_mass_g'] / np.mean(x['flipper_length_mm'])))

species    sex   
Adelie     FEMALE    17.938945
           MALE      21.014880
Chinstrap  FEMALE    18.396226
           MALE      19.703546
Gentoo     FEMALE    22.000892
           MALE      24.757659
dtype: float64

In [ ]:
penguin.groupby('species').transform(np.mean)

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0         38.791391      18.346358         189.953642  3700.662252
1         38.791391      18.346358         189.953642  3700.662252
2         38.791391      18.346358         189.953642  3700.662252
3         38.791391      18.346358         189.953642  3700.662252
4         38.791391      18.346358         189.953642  3700.662252
..              ...            ...                ...          ...
339       47.504878      14.982114         217.186992  5076.016260
340       47.504878      14.982114         217.186992  5076.016260
341       47.504878      14.982114         217.186992  5076.016260
342       47.504878      14.982114         217.186992  5076.016260
343       47.504878      14.982114         217.186992  5076.016260

[344 rows x 4 columns]

In [ ]:
df

year  pop  debt  debt_2  new_column
first   2000  1.5   NaN     NaN         NaN
second  2001  1.7   NaN    -1.2         NaN
third   2002  3.6   NaN     NaN         NaN
fourth  2001  2.4   NaN    -1.5         NaN
fifth   2002  2.9   NaN    -1.7         NaN
sixth   2003  3.2   NaN     NaN         NaN

In [ ]:
df = penguin.groupby(['species', 'sex']).mean()
df.to_csv('my_file.csv', sep='\t')

### Multiindex reshape pivot e melt

In [ ]:
df3 = penguin.groupby(['species', 'sex']).apply(lambda x : np.mean(x['body_mass_g'] / np.mean(x['flipper_length_mm'])))
df3

species    sex   
Adelie     FEMALE    17.938945
           MALE      21.014880
Chinstrap  FEMALE    18.396226
           MALE      19.703546
Gentoo     FEMALE    22.000892
           MALE      24.757659
dtype: float64

In [ ]:
df3.index

MultiIndex([(   'Adelie', 'FEMALE'),
            (   'Adelie',   'MALE'),
            ('Chinstrap', 'FEMALE'),
            ('Chinstrap',   'MALE'),
            (   'Gentoo', 'FEMALE'),
            (   'Gentoo',   'MALE')],
           names=['species', 'sex'])

In [ ]:
df3.unstack('species')

species     Adelie  Chinstrap     Gentoo
sex                                     
FEMALE   17.938945  18.396226  22.000892
MALE     21.014880  19.703546  24.757659

In [ ]:
data = pd.Series(np.random.randn(9), index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'], [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1    0.347823
   2   -1.040296
   3   -0.044514
b  1   -0.654511
   3   -0.920749
c  1    1.663736
   2    0.791569
d  2   -0.720418
   3    1.261404
dtype: float64

In [ ]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [ ]:
data.loc[:, 2]

a   -1.040296
c    0.791569
d   -0.720418
dtype: float64

In [ ]:
data.unstack()

1         2         3
a  0.347823 -1.040296 -0.044514
b -0.654511       NaN -0.920749
c  1.663736  0.791569       NaN
d       NaN -0.720418  1.261404

In [ ]:
data.unstack().loc[:, 2]

a   -1.040296
b         NaN
c    0.791569
d   -0.720418
Name: 2, dtype: float64

In [ ]:
data.unstack().stack()

a  1    0.347823
   2   -1.040296
   3   -0.044514
b  1   -0.654511
   3   -0.920749
c  1    1.663736
   2    0.791569
d  2   -0.720418
   3    1.261404
dtype: float64

In [ ]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)), index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]], columns=[['Ohio', 'Ohio', 'Colorado'], ['Green', 'Red', 'Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [ ]:
frame.sum(level=0, axis=0)

Ohio     Colorado
  Green Red    Green
a     3   5        7
b    15  17       19

In [ ]:
frame.sum(level=1, axis=1)

Green  Red
a 1      2    1
  2      8    4
b 1     14    7
  2     20   10

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Projects/Python course/macrodata_long.csv', index_col=0)
data.head()

date     item     value
0  1959-03-31 23:59:59.999999999  realgdp  2710.349
1  1959-03-31 23:59:59.999999999     infl     0.000
2  1959-03-31 23:59:59.999999999    unemp     5.800
3  1959-06-30 23:59:59.999999999  realgdp  2778.801
4  1959-06-30 23:59:59.999999999     infl     2.340

In [ ]:
data.pivot('date', 'item', 'value').head()

item                           infl   realgdp  unemp
date                                                
1959-03-31 23:59:59.999999999  0.00  2710.349    5.8
1959-06-30 23:59:59.999999999  2.34  2778.801    5.1
1959-09-30 23:59:59.999999999  2.74  2775.488    5.3
1959-12-31 23:59:59.999999999  0.27  2785.204    5.6
1960-03-31 23:59:59.999999999  2.31  2847.699    5.2

In [ ]:
data.set_index(['date', 'item'])

value
date                          item              
1959-03-31 23:59:59.999999999 realgdp   2710.349
                              infl         0.000
                              unemp        5.800
1959-06-30 23:59:59.999999999 realgdp   2778.801
                              infl         2.340
...                                          ...
2009-06-30 23:59:59.999999999 infl         3.370
                              unemp        9.200
2009-09-30 23:59:59.999999999 realgdp  12990.341
                              infl         3.560
                              unemp        9.600

[609 rows x 1 columns]

In [ ]:
data.set_index(['date', 'item']).unstack('item').head()

value                
item                           infl   realgdp unemp
date                                               
1959-03-31 23:59:59.999999999  0.00  2710.349   5.8
1959-06-30 23:59:59.999999999  2.34  2778.801   5.1
1959-09-30 23:59:59.999999999  2.74  2775.488   5.3
1959-12-31 23:59:59.999999999  0.27  2785.204   5.6
1960-03-31 23:59:59.999999999  2.31  2847.699   5.2

In [ ]:
data.set_index(['date', 'item']).unstack('item').head()

In [ ]:
df = pd.DataFrame({'key': ['foo', 'bar', 'baz'], 'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
df

In [ ]:
df.melt('key')

In [ ]:
df.set_index('key').stack().reset_index()

### Merge e concat

In [ ]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'], 'data': range(3)})

df1

In [ ]:
df2

In [ ]:
pd.merge(df1, df2, on='key')

In [ ]:
pd.merge(df1, df2, on='key', how='inner', suffixes=['_left', '_right'])

In [ ]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])

s1

In [ ]:
pd.concat([s1, s2, s3], axis=0)

In [ ]:
pd.concat([s1, s2, s3], axis=1)

In [ ]:
s4 = pd.concat([s1, s3])
s4

In [ ]:
pd.concat([s1, s4], axis=1)

In [ ]:
pd.concat([s1, s4], axis=1, join='inner')

In [ ]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'], columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'], columns=['three', 'four'])

df1

In [ ]:
df2

In [ ]:
pd.concat([df1, df2], axis=1, keys=['first', 'second'])

In [ ]:
pd.concat([df1, df2], axis=0, keys=['first', 'second'])

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Projects/Python course/data.csv', sep='\t')
metadata = pd.read_csv('/content/drive/MyDrive/Projects/Python course/metadata.csv', sep='\t')

In [ ]:
data.head()

In [ ]:
metadata.head()

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Projects/Python course/data.csv', sep='\t', index_col=0)
data.head()

In [ ]:
metadata = pd.read_csv('/content/drive/MyDrive/Projects/Python course/metadata.csv', sep='\t', skiprows=1, names=['sample_name', 'param_name', 'value'])
metadata.head()

In [ ]:
metadata = metadata.pivot('sample_name', 'param_name', 'value')
metadata

In [ ]:
data[metadata[metadata['param_0'] == 'A'].index].mean(axis=1)

In [ ]:
data.columns = pd.MultiIndex.from_tuples(zip(data.columns, metadata['param_0'].values))
data

In [ ]:
data.mean(level=1, axis=1)

In [ ]:
# Modify yesterday exercise in order to get for each word: the word count, the songs, album name, album year

In [ ]:
dir = '/content/drive/MyDrive/Projects/Physalia-courses/Python/2022/Dataset/beatles'
song_list_file = dir + '/' + 'song_list.txt'

In [ ]:
def get_song_list(filename):
  song_list = {}
  current_id = ''
  with open(filename) as f:
    for l in f:
      if l.startswith('='):
        continue
      s = l.strip().split('=')
      if s[0] == 'ID':
        current_id = s[1]
        song_list[current_id] = ['', '']
      elif s[0] == 'SONG':
        song_list[current_id][0] = s[1]
      elif s[0] == 'FILE':
        song_list[current_id][1] = s[1]
  return song_list

In [ ]:
import re

def update_words(first, second):
    return {k: first.get(k, 0) + second.get(k, 0) for k in set(list(first.keys()) + list(second.keys()))}

def get_word_count(filename):
    all_words = {}
    pattern = r'\w+'
    year = -1
    album = ''
    end_of_text = False
    with open(filename) as f:
        [next(f) for _ in range(8)]
        for l in f:
            if not l.strip():
                continue
            if l.strip() == 'Correct lyrics':
                end_of_text = True
                continue
            if not end_of_text:
              words = re.findall(pattern, l.strip().lower())
              words = {k: words.count(k) for k in words}
              all_words = update_words(words, all_words)  
            else:
              year = l.strip()[-5:-1]
              album = l[:l.find('(')].strip()
              break
    return all_words, year, album

            
def word_count(song_filename):
  ln = 1
  words = {}
  end_of_text = False
  year = -1
  album = ''
  with open(song_filename) as f:
    for i in range(8):
      next(f)
    for l in f:
      if not l.strip():
        continue
      if l.strip().startswith('Correct lyrics'):
        end_of_text = True
        continue
      if not end_of_text:
        s = l.strip().replace(',', '').replace('"', '').replace('(fade out)', '').split(' ')
        for _x in s:
          if _x not in words:
            x = _x.lower()
            words[x] = 0
          words[x] += 1
      else:  
        year = l.strip()[-5:-1]
        album = l[:l.find('(')].strip()
        break
  return words, int(year), album

In [ ]:
import os

song_list = get_song_list(song_list_file)
words = []
for _id, song in song_list.items():
  w, y, a = get_word_count(os.path.join(dir, song[1]))
  df = pd.DataFrame({k: [v, y, a, song[0]] for k, v in w.items()}).T
  df.columns = ['word count', 'year', 'album', 'song']
  words.append(df)
  #for k, v in w.items():
  #  if k not in words:
  #    words[k] = 0
  #  words[k] += v

In [ ]:
beatles_df = pd.concat(words, axis=0)

In [ ]:
beatles_df.loc['love'].sort_values(by='word count', ascending=False)

word count  year                    album                           song
love         64  1967     Magical Mystery Tour           All You Need Is Love
love         24  1963         Please Please Me                     Love Me Do
love         22  1964         Beatles For Sale              Eight Days A Week
love         22  1994  Live At The BBC. Disk 1     To Know Her Is To Love Her
love         20  1994  Live At The BBC. Disk 2                   Ooh! My Soul
...         ...   ...                      ...                            ...
love          1  2017    The Christmas Records  The Beatles' Christmas Record
love          1  1964       A Hard Day's Night                    Tell Me Why
love          1  1965                    Help!               Dizzy Miss Lizzy
love          1  1994  Live At The BBC. Disk 1                 From Us To You
love          1  1963         Please Please Me                There's A Place

[127 rows x 4 columns]

In [ ]:
beatles_df.reset_index().groupby('index').count().sort_values(by='song', ascending=False)

word count  year  album  song
index                                   
the               245   245    245   245
you               242   242    242   242
i                 240   240    240   240
to                238   238    238   238
and               229   229    229   229
...               ...   ...    ...   ...
measure             1     1      1     1
measured            1     1      1     1
medicinem           1     1      1     1
mediocre            1     1      1     1
boldly              1     1      1     1

[4000 rows x 4 columns]

In [ ]:
beatles_df.groupby(['year', 'album']).count()

word count  song
year album                                                  
-1                                                1084  1084
1963 Please Please Me                              713   713
     With The Beatles                              762   762
1964 A Hard Day's Night                            837   837
     Beatles For Sale                              816   816
1965 Help!                                         906   906
     Rubber Soul                                   954   954
1966 Revolver                                      946   946
1967 Magical Mystery Tour                          666   666
     Sgt. Pepper's Lonely Hearts Club Band        1221  1221
1968 The Beatles                                  2151  2151
1969 Abbey Road                                    863   863
     Yellow Submarine                              301   301
1970 Let It Be                                     752   752
1988 Past Masters. Volume One                      978   978
     Past Masters. Volume Two                      881   881
1994 Live At The BBC. Disk 1                      1720  1720
     Live At The BBC. Disk 2                      1239  1239
1995 Anthology 1                                   973   973
1996 Anthology 2                                   203   203
     Anthology 3                                   460   460
2006 Love                                            4     4
2017 The Christmas Records                        1555  1555

In [ ]:
beatles_df[['album', 'song']].drop_duplicates().groupby(['album', 'song']).count().index

MultiIndex([(                  '',                                'ILE'),
            ('A Hard Day's Night',                 'A Hard Day's Night'),
            ('A Hard Day's Night',                     'And I Love Her'),
            ('A Hard Day's Night',                    'Any Time At All'),
            ('A Hard Day's Night',                  'Can't Buy Me Love'),
            ('A Hard Day's Night',         'I Should Have Known Better'),
            ('A Hard Day's Night',                       'I'll Be Back'),
            ('A Hard Day's Night',                   'I'll Cry Instead'),
            ('A Hard Day's Night',   'I'm Happy Just To Dance With You'),
            ('A Hard Day's Night',                          'If I Fell'),
            ...
            (  'Yellow Submarine',                   'All Together Now'),
            (  'Yellow Submarine',                        'Hey Bulldog'),
            (  'Yellow Submarine',                  'It's All Too Much'),
            (  'Yellow